Feature/storybook setup
nearshorecode/web-ui pull request #3
Opened 2018-02-15 21:02 UTC by hdwilber

# StoryBook Configuration
This PR includes Storybook.js configuration to display the components in a fashion way. 
- it has included addon-info to show source code and props information about the component.
- It has a CSS file inside `/stories` in order to highlight the component itself.
- To run the storybook server: `npm run storybook`. then, it will be listening in `port 9001`
- To create a bundled built: `npm run storybook:build`. then, a folder `/build/storybook/` will be created with static files.

- Currently, It uses as example `ImageTag` component. It seems the component is not working fine 🤣

2018-02-15 21:10 UTC, diegolanda requested changes

2018-02-15 21:10 UTC, diegolanda commented on .env
> -NODE_PATH=src
We are using absolute imports, if we decide not to use .env then we need to add aliases in webpack.config. Please add those changes so we keep importing like `components/Layouts` or `components`

2018-02-15 21:10 UTC, diegolanda commented on src/App.js
> +import { ImageTag } from './components';
We would miss absolute imports

2018-02-15 21:12 UTC, diegolanda commented on .env
> -NODE_PATH=src
Maybe other configuration like this https://medium.com/@kkomaz/another-solution-to-absolute-path-setup-in-create-react-app-cccb38d8eea8 @hdwilber

2018-02-15 21:35 UTC, oscarfgq approved these changes

2018-02-17 19:55 UTC, diegolanda approved these changes

2018-02-18 03:33 UTC, merged